### ISSUE TITLE
zeva prefix

### ISSUE THREAD

**Issue by JLammeer** [zeva-ui/zeva#12]
Creating a custom prefix for class names would avoid conflicts with users code.

Prefixes examples:

- zv-block--element__modifier;
- zeva-block--element__modifier.

**Comment by JLammeer** [comment]
@imfunniee & @Kvanrooyen 

What do you say, boys?! Is it a good idea?

**Comment by imfunniee** [comment]
👌

**Comment by Kvanrooyen** [comment]
:ok_hand: seems good

**Comment by JLammeer** [comment]
If we decide to use BEVM, selectors using these prefixes would be too long (polluted maybe?). So It's better to close this issue and re-open it if we decide to go with a more concise naming system.
