### ISSUE TITLE
animations

### ISSUE THREAD

**Issue by JLammeer** [zeva-ui/zeva#13]
It is important to support users with default animations, so they won't need to bother with it.

Although, I should note that this feature must be optional, so users can choose to use it or not by toggling a Sass variable value.

**Comment by oliver-gomes** [comment]
Hey @JLammeer,
I am Jonsnow lol
Anyway I am writing my thoughts here.
I feel simple animations like that can be made in CSS should do the trick as of course anime.js already exists we should not bother working on something like that

**Comment by imfunniee** [comment]
ye its a great idea but i was thinking about having a pulse animation, something similar to this https://codepen.io/Tipue/pen/pOWLPy

**Comment by oliver-gomes** [comment]
@imfunniee sure totally doable

**Comment by oliver-gomes** [comment]
So on pulse side, we can have click-pulse which can be onetime when clicked and another can be forever and other similar variations

**Comment by imfunniee** [comment]
ye 👍, but not the forever animation we can have that on a incoming notification (yes future version will have that) or warning

**Comment by oliver-gomes** [comment]
@imfunniee I am creating an animation.scss to keep all the animations in one place and it's in the directory components, does it sounds good or you want me to put it in other directory?

**Comment by JLammeer** [comment]
@oliver-gomes Seems perfect to me, at least.

**Comment by oliver-gomes** [comment]
Made a PR you guys can review it 😄

**Comment by JLammeer** [comment]
Oliver's PR should be enough to deliver on v1.0.0.
