### ISSUE TITLE
improve README file

### ISSUE THREAD

**Issue by JLammeer** [zeva-ui/zeva#20]
Still there isn't enough information in this file.

**Comment by Kvanrooyen** [comment]
A good example to use as reference. 
https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

**Comment by JLammeer** [comment]
That's perfect! I'll start it in a moment.

**Comment by JLammeer** [comment]
Done! -> https://github.com/zeva-ui/zeva/commit/bee9e88f66d386b3091a852ac30735b31ba29c84
