### ISSUE TITLE
create tag for v1.0.0 and start using SemVer

### ISSUE THREAD

**Issue by JLammeer** [zeva-ui/zeva#24]
When we get things ready for v1.0.0 release, we should start using SemVer.

Of course, we should've be doing this earlier, but that's not the case.

**Comment by imfunniee** [comment]
https://github.com/zeva-ui/zeva/releases??

**Comment by JLammeer** [comment]
Yep, we would use GitHub release system. 

In addition to that, we also would need to bump the version in our npm `package.json` file (before Github release).

**Comment by imfunniee** [comment]
https://github.com/zeva-ui/zeva/releases/tag/v1.0.0-beta, close this issue??

**Comment by JLammeer** [comment]
@imfunniee Yeah, let's close it. Just don't forget to manage the versions properly, according to [SemVer 2.0.0](https://semver.org/).
