### ISSUE TITLE
A few typos in the docs.

### ISSUE THREAD

**Issue by leerob** [zeva-ui/zeva#36]
https://github.com/zeva-ui/zeva/blob/08f777fb39bdba01a9840a954426c83a431dfada/samples/form.html#L22-L26

**Comment by Kvanrooyen** [comment]
Thanks. I'll have a look into getting that sorted.

**Comment by Kvanrooyen** [comment]
@leerob I made some changes [here.](https://github.com/zeva-ui/zeva/pull/37)
