### ISSUE TITLE
create slack for the community.

### ISSUE THREAD

**Issue by JLammeer** [zeva-ui/zeva#7]
Gotta discuss creating a slack for the community.

**Comment by JLammeer** [comment]
Hey, @Kvanrooyen ?!

As you are working on the Discord server, can you tell us what are your thoughts on slack rooms? Do you think it would be worth creating?

**Comment by Kvanrooyen** [comment]
Hey @JLammeer

I think we should use Discord for the community, and use slack rooms for the development team. I am open to ideas
